[package]
name = "datafusion-index-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "32.0"
arrow = "47.0"
futures = "0.3"

[dev-dependencies]
tokio = { version = "1.36", features = ["full", "macros", "rt-multi-thread"] }
async-trait = "0.1"
