[package]
name = "datafusion-index-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
datafusion = "46.0.1"
datafusion-common = "46.0.1"
arrow = "54.3.1"
futures = "0.3.26"
futures-util = "0.3.30"
futures-core = "0.3.30"
log = "0.4.20"
parking_lot = "0.12.0"

[dev-dependencies]
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
env_logger = "0.11.2"
